// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPaulo.Data.Context;

namespace ProjetoPaulo.Data.Migrations
{
    [DbContext(typeof(PauloContext))]
    partial class PauloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Exemplo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ex_id");

                    b.Property<string>("Descricao")
                        .HasColumnName("ex_descricao");

                    b.HasKey("Id")
                        .HasName("pk_tb_exemplo");

                    b.ToTable("tb_exemplo");
                });
#pragma warning restore 612, 618
        }
    }
}
